version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3-alpine
    resource_class: small
    steps:
      - checkout
      - run: python main.py
workflows:
    build-and-test:
      jobs:
        - build-and-test
