version: 2.1

jobs:
  build-and-test:
    docker:
      - image: golang:alpine
    resource_class: small
    steps:
      - checkout
      - run: go run main.go
workflows:
    build-and-test:
      jobs:
        - build-and-test
