version: 2.1

jobs:
  build-and-test:
    docker:
      - image: node:14.4.0-alpine3.10
    resource_class: small
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
